web:
  build: .
  command: bash runserver.sh
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=${user}
    - MYSQL_PASSWORD=${password}
    - MYSQL_DATABASE=${database}
    # - MYSQL_USER=test
    # - MYSQL_PASSWORD=test
    # - MYSQL_DATABASE=test